#!/bin/bash


echo 'STARTING SEQUENTIAL DOWNLOAD PROCESS'

xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_1.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_10.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_100.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_101.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_102.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_103.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_104.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_105.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_106.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_107.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_108.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_109.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_11.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_110.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_111.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_112.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_113.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_114.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_115.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_116.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_117.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_118.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_119.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_12.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_120.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_121.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_122.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_13.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_14.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_15.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_16.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_17.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_18.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_19.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_2.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_20.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_21.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_22.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_23.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_24.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_25.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_26.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_27.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_28.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_29.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_3.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_30.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_31.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_32.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_33.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_34.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_35.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_36.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_37.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_38.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_39.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_4.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_40.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_41.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_42.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_43.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_44.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_45.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_46.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_47.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_48.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_49.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_5.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_50.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_51.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_52.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_53.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_54.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_55.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_56.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_57.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_58.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_59.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_6.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_60.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_61.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_62.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_63.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_64.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_65.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_66.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_67.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_68.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_69.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_7.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_70.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_71.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_72.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_73.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_74.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_75.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_76.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_77.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_78.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_79.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_8.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_80.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_81.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_82.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_83.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_84.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_85.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_86.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_87.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_88.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_89.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_9.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_90.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_91.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_92.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_93.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_94.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_95.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_96.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_97.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_98.root /mnt/e/PROJECT_DATA/ROOT_FILES/
xrdcp root://eospublic.cern.ch//eos/opendata/cms/datascience/JetNtupleProducerTool/JetNTuple_QCD_RunII_13TeV_MC/JetNtuple_RunIISummer16_13TeV_MC_99.root /mnt/e/PROJECT_DATA/ROOT_FILES/

echo 'FILE DOWNLOAD COMPLETE'